version: '3.8'

services:
  app:
    container_name: openbazaar3 
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:8080
      - 4002:4002
    command: ["openbazaar3", "start"]
